# Generated by Django 2.0.7 on 2018-09-28 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='out_trade_num',
            field=models.UUIDField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='trade_no',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
